/**
 * This file was generated by the Jeddict
 */
package EntityClasses;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Entity;


import javax.persistence.ManyToOne;


/**
 * @author John Linus
 */
@Entity

public class Student extends Person implements Serializable {

    @ManyToOne(cascade=CascadeType.PERSIST)
    
    
    
    
    private Education education;

    public Student(Education education, String firstName, String lastName, int age) {
        super(firstName, lastName, age);
        this.education = education;
    }

    public Student(String firstName, String lastName, int age) {
        super(firstName, lastName, age);
    }
    
    
    
    public Student() {
    }
    
    
    public Education getEducation() {
        return this.education;
    }

    

    public void setEducation(Education education) {
        this.education = education;
    }

    @Override
    public String toString() {
        return "Student{" + super.toString()  + education + '}';
    }


    
    
    
    

}