/**
 * This file was generated by the Jeddict
 */
package EntityClasses;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;

/**
 * @author John Linus
 */
@Entity
public class Teacher extends Person {

    @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    private List<Course> courses;

    public Teacher(String firstName, String lastName, int age) {
        super(firstName, lastName, age);
    }

    public Teacher() {
    }

    public List<Course> getCourses() {
        if (courses == null) {
            courses = new ArrayList<>();
        }

        return this.courses;
    }

    public void setCourses(List<Course> courses) {
        this.courses = courses;
    }

    public void addCourse(Course course) {
        getCourses().add(course);
        course.getTeachers().add(this);

    }

    public void removeCourse(Course course) {
        getCourses().remove(course);
        course.getTeachers().remove(this);
    }

    @Override
    public String toString() {
        return super.toString() + " / " + courses + '}';
    }

}
